services:
    web:
        build: ./web
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ../hht/hanhuang.tech:/usr/share/nginx/html/hanhuang.tech
            - ../hht/clothingsite:/usr/share/nginx/html/clothingsite
            - /var/lib/docker/volumes/certs:/etc/letsencrypt
