services:
    web:
        build: ./web
        ports:
            - "80:80"
            - "443:443"
            - "9000:9000"
        volumes:
            - ./web/conf/nginx.conf:/etc/nginx/nginx.conf
            - ./web/conf/hanhuang.tech.conf:/etc/nginx/conf.d/hanhuang.tech.conf
            - ./web/conf/clothingsite.conf:/etc/nginx/conf.d/clothingsite.conf
            - ../hht/hanhuang.tech:/usr/share/nginx/html/hanhuang.tech
            - ../hht/clothingsite:/usr/share/nginx/html/clothingsite	
            - ./certbot_gen/certs:/etc/letsencrypt
        env_file:
            - var.env
        environment:
            - IP4=$IP4
            - AZ=$AZ
    cert-renew:
        build: ./cert_renew
        volumes:
            - ./certbot_gen/certs:/etc/letsencrypt

