services:
    web:
        build: ./web
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./web/conf/nginx.conf:/etc/nginx/nginx.conf
            - ./web/conf/hanhuang.tech.conf:/etc/nginx/conf.d/hanhuang.tech.conf
            - ./web/conf/clothingsite.conf:/etc/nginx/conf.d/clothingsite.conf
            - ./web/html:/usr/share/nginx/html/
            - ../hht/hanhuang.tech:/usr/share/nginx/html/hanhuang.tech
            - ../hht/clothingsite.hanhuang.tech:/usr/share/nginx/html/clothingsite	
            - ./certbot_gen/certs:/etc/letsencrypt
    cron:
        image: alpine:latest
        command: crond -f -l 8
        ports:
            - "2000:2000"
        volumes:
            - ./cronjobs:/etc/crontabs/root
            - ./certbot_gen/certs:/etc/letsencrypt

