services:
    web:
        build: ./web
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./web/conf/nginx.conf:/etc/nginx/nginx.conf
            - ./web/conf/hanhuang.tech.conf:/etc/nginx/conf.d/hanhuang.tech.conf
            - ./web/conf/clothingsite.conf:/etc/nginx/conf.d/clothingsite.conf
            - ./web/html:/usr/share/nginx/html/
            - ../hht/hanhuang.tech:/usr/share/nginx/html/hanhuang.tech
            - ../hht/clothingsite:/usr/share/nginx/html/clothingsite	
            - ../hht/error-pages:/usr/share/nginx/html/error-pages
            - ./certbot_gen/certs:/etc/letsencrypt
    cert-renew:
        build: ./cert_renew
        volumes:
            - ./certbot_gen/certs:/etc/letsencrypt

